ProfileApp/Models/ApplicationDBContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProfileApp.Models
{
    public class ApplicationDBContext : DbContext
    {
        public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options) : base(options)
        {

        }

        public DbSet<Profile> Profiles { get; set; }
    }
}

ProfileApp/Models/ErrorViewModel.cs
using System;

namespace ProfileApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProfileApp/Models/Profile.cs
using System.ComponentModel.DataAnnotations;

namespace ProfileApp.Models
{
    public class Profile
    {
        [Key]
        public int Id { get; set; }

        public string Photo { get; set; }

        [Required(ErrorMessage ="Enter firstname")]
        public string Firstname { get; set; }

        [Required]
        public string Surname { get; set; }

        [Required]
        public string Description { get; set; }

        public string Website { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Phone { get; set; }
    }
}

ProfileApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProfileApp.Models;

namespace ProfileApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProfileApp/Controllers/ProfilesAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ProfileApp.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class ProfilesAPIController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        public ProfilesAPIController()
        {
            
        }

        private readonly ILogger<ProfilesAPIController> _logger;

        public ProfilesAPIController(ILogger<ProfilesAPIController> logger)
        {
            _logger = logger;
        }

    }
}

ProfileApp/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProfileApp.Models;

namespace ProfileApp.Controllers
{

    public class ProfilesController : Controller
    {
        private readonly ApplicationDBContext _db;

        public ProfilesController(ApplicationDBContext db)
        {
            _db = db;
        }


        [BindProperty]
        public Profile Profile{ get; set; }
        public IActionResult Index()
        {
            var displaydata = _db.Profiles.ToList();
            return View(displaydata);
        }



        #region API Calls

        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Profiles.ToListAsync() });
        }

        public async Task<IActionResult> Profilespage(int id)
        {
            var profileFromDB = await _db.Profiles.FirstOrDefaultAsync(u => u.Id == id);
            if (profileFromDB == null)
            {
                return Json(new { success = false, message = "Error Viewing Profile" });
            }
            return View(profileFromDB);

        }
        #endregion
    }
}

ProfileApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron row">
    <div class="col-4"><img src="profpic.jpg" alt="Mfanomutsha Picture"/></div>
    <div class="col-8">
       <h1>Mfanomutsha Ncube</h1>
        <div class="row">
            Why do we use it?
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
        </div>
        <div class="row text-success">www.firstname.co.za | info@firstname.co.za | 0739 303 098</div>
        <div class="row btns">
            <button class="btn btn-success">Visit Website</button>
            <button class="btn btn-success">Request CV</button>
        </div>
        <div class="row pt-2 btns">
            <button class="btn btn-success">First</button>
            <button class="btn btn-success">Previous</button>
            <button class="btn btn-success">Next</button>
            <button class="btn btn-success">Last</button>
        </div>
    </div>
</div>

ProfileApp/Views/Profiles/Index.cshtml
@model IEnumerable<ProfileApp.Models.Profile>

<br />
<div class="jumbotron">
    <h1 class="text-center">Welcome to the Developers profile</h1>
    <br />
    <table id="DT_load" class="table table-hover table-responsive">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Firstname)</th>
                <th>@Html.DisplayNameFor(model => model.Surname)</th>
                <th>@Html.DisplayNameFor(model => model.Website)</th>
                <th>@Html.DisplayNameFor(model => model.Email)</th>
                <th>@Html.DisplayNameFor(model => model.Phone)</th>
                <th>Action</th>
            </tr>
        </thead>

    </table>


</div>


@section scripts {
    <script src="~/js/Profiles.js"></script>
}

ProfileApp/Views/Profiles/Profilespage.cshtml
@model ProfileApp.Models.Profile

<br />
<div class="jumbotron row">
   
            @if (Model.Id != 0)
            {
                <div class="col-4"><img src="/@Html.DisplayFor(modelItem => Model.Photo)" alt="@Html.DisplayFor(modelItem => Model.Firstname) Picture" /></div>
                <div class="col-8">
                   <h2> @Html.DisplayFor(modelItem => Model.Firstname)  @Html.DisplayFor(modelItem => Model.Surname)</h2>
                    <div class="row">
                        @Html.DisplayFor(modelItem => Model.Description)
                    </div>
                    <div class="row text-success">@Html.DisplayFor(modelItem => Model.Website) | @Html.DisplayFor(modelItem => Model.Email) | @Html.DisplayFor(modelItem => Model.Phone)</div>
                    <div class="row btns">
                        
                            <a href="http://@Html.DisplayFor(modelItem => Model.Website)" target="_blank" class="btn  form-control">Visit Website</a>  <br /><br />
                            <a asp-action="Index" class="btn btn-success form-control">Request CV</a>
                      
                    </div>
                    <div class="row pt-2 btns">
                        <a asp-action="Index" class="btn form-control">Back to Dev List</a>
                    </div>
                </div>
            }
</div>

@section scripts{
    <partial name="_validationScriptsPartial" />
}

ProfileApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProfileApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Developer Profile</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action=""> View More Profiles </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ProfileApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>